# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corArma <- function(X, norm_type) {
    .Call('correlateR_corArma', PACKAGE = 'correlateR', X, norm_type)
}

crosscorArma <- function(X, Y, norm_type) {
    .Call('correlateR_crosscorArma', PACKAGE = 'correlateR', X, Y, norm_type)
}

corEigen <- function(X, norm_type = 0L) {
    .Call('correlateR_corEigen', PACKAGE = 'correlateR', X, norm_type)
}

crosscorEigen <- function(X, Y, norm_type = 0L) {
    .Call('correlateR_crosscorEigen', PACKAGE = 'correlateR', X, Y, norm_type)
}

cube <- function(x) {
    .Call('correlateR_cube', PACKAGE = 'correlateR', x)
}

covArma <- function(X, norm_type) {
    .Call('correlateR_covArma', PACKAGE = 'correlateR', X, norm_type)
}

crosscovArma <- function(X, Y, norm_type) {
    .Call('correlateR_crosscovArma', PACKAGE = 'correlateR', X, Y, norm_type)
}

covEigen <- function(X, norm_type = 0L) {
    .Call('correlateR_covEigen', PACKAGE = 'correlateR', X, norm_type)
}

crosscovEigen <- function(X, Y, norm_type = 0L) {
    .Call('correlateR_crosscovEigen', PACKAGE = 'correlateR', X, Y, norm_type)
}

